#!/usr/bin/env python3
import configargparse
import slackboy as sb

parser = configargparse.ArgumentParser()
parser.add_argument("--message", type=str, required=True, help="msg to send")
parser.add_argument("--channel", type=str, required=True, help="slack channel")
args = parser.parse_args()

slackboy = sb.SlackBoy.from_config()
slackboy.send_message(msg=args.message, channel=args.channel)
