name: restart process after deployment

on:
  workflow_call:
    inputs:
      user:
        description: edge device username
        required: true
        type: string
      code-name:
        description: code module name
        required: true
        type: string
      deploy-branch:
        description: branch to be deployed
        default: main
        required: false
        type: string
      parent-dir:
        description: code directory of the edge device
        required: true
        type: string
      version-file-name:
        description: _version_.py or .version
        required: true
        type: string
    secrets:
      tailscale-authkey:
        description: tailscale authkey to add runner to the tailnet
        required: true
      password:
        description: edge device password
        required: true
      otp:
        description: edge device otp
        required: true

jobs:
  restart-after-deploy:
    name:   restart-after-deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Add runner to the tailnet
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.tailscale-authkey }}

      - name: Checkout the deploy-target repository
        uses: actions/checkout@v2

      - name: Checkout the action repository
        uses: actions/checkout@v2
        with:
          repository: teamdable/vv-deploy-actions
          path: action/

      - name: Setup python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install python packages for api call
        run: |
          python3 -m pip install --upgrade pip
          pip install -r action/requirements.txt

      - name: Get VPN IP of deploy-target devices
        run: |
          python3 action/get-vpn-ip

      - name: Kill and Start process
        run: |
          sudo apt-get install expect oathtool
          action/restart_process_after_deploy.sh ${{ inputs.user }} ${{ secrets.password }} ${{ secrets.otp }} ${{ inputs.parent-dir }} ${{ inputs.code-name }}